apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/udamale/Kubernetes-end-to-end-project.git
    targetRevision: HEAD
    path: Kubernetes-Manifests-file//Backend
  destination: 
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
