apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/udamale/Kubernetes-end-to-end-project.git
    targetRevision: HEAD
    path: Kubernetes-Manifests-file//Frontend
  destination: 
    server: https://kubernetes.default.svc
    namespace: frontend

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true